INSERT INTO public.rotas(origem, destino, valor) VALUES ( 'GRU', 'BRC', 10);
INSERT INTO public.rotas(origem, destino, valor) VALUES ( 'BRC', 'SCL', 5);
INSERT INTO public.rotas(origem, destino, valor) VALUES ( 'GRU', 'CDG', 75);
INSERT INTO public.rotas(origem, destino, valor) VALUES ( 'GRU', 'SCL', 20);
INSERT INTO public.rotas(origem, destino, valor) VALUES ( 'GRU', 'ORL', 56);
INSERT INTO public.rotas(origem, destino, valor) VALUES ( 'ORL', 'CDG', 5);
INSERT INTO public.rotas(origem, destino, valor) VALUES ( 'SCL', 'ORL', 20);